### ISSUE TITLE
nth-child选择器

### ISSUE THREAD

**Issue by zebratt** [zebratt/thoughts#51]
之前一直以为：
 
`.classA:nth-child(1)`

选择到的是所有class为classA的元素中，第一个。实际上不是，看一个栗子：

```html
<div class="a">
  <p>ppp</p>
  <div class="b">b</div>
  <div class="c">c</div>
  <div class="d">d</div>
</div>
</body>
```

```css
.a div{
  margin-top: 10px;
  width: 200px;
  background: #abc;
}

.a div:nth-child(1) {
  background: red;
}

.a div:nth-child(2) {
  background: blue;
}
```

此时会出现什么情况呢？

![image](https://user-images.githubusercontent.com/7269427/93964765-11455e00-fd93-11ea-9e9f-6e78ce09158d.png)

可见，第一个元素实际上是 P，第二个元素才是b。所以，可以得到结论是nth-child选择器实际上选择的是同一父级下，所有的元素。
